import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
//Bootstrap
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/component/common/Footer";

export const metadata = {
  title: "Knit Software",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=1"],
    apple: ["/apple-touch-icon.png?v=1"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ marginTop: "-100px" }}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
