info:
  application:
    name: 'knit software backend'
    description: 'This is the backend of knit software app'
    version: '0.0.1-SNAPSHOT'

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/knit_software_db
    username: db_knit
    password: db_knit_software
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: knitsoftware@gmail.com
#      password: rqqr zqwb bqvm reym
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true

#image
servlet:
  multipart:
    max-file-size: 2MB
    max-request-size: 2MB


management:   # actuator monitorleme icin
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "health,info,'loggers','env','beans'"
    web:
      exposure:
        include: ['health','loggers','env','beans']
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true



knit_software:
  app:
    jwtSecret: AppSecretKeyQAppSecretKeyQAppSecretKeyQAppSecretKeyQAppSecretKeyQAppSecretKeyQAppSecretKeyQAppSecretKeyQ
    jwtExpirationMs: 86400000
