info:
  application:
    name: 'knit software backend'
    description: 'This is the backend of knit software app'
    version: 'project.version@'

server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_v2_db
    username: db_knit
    password: db_knit_software
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: knitsoftware@gmail.com
#      password: rqqr zqwb bqvm reym
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true

